### ISSUE TITLE
dead link in README.md

### ISSUE THREAD

**Issue by nilswald** [mrwatson-de/fmLaunchPad#2]
404: https://www.fmworkmate.com/fmlaunchpad

**Comment by mrwatson-de** [comment]
Hi,

thanks Nils - I know ... that's a problem due to my website, recently taken over by a different hosting company, where fmWorkMate.com domain is not handling subpages properly.

MrWatson.de and fmWorkMate.com should be identical - they point to the same sites, but they are registered with different providers and fmWorkMate.com has broken during the move.

http://www.mrwatson.de/fmlaunchpad <http://www.mrwatson.de/fmlaunchpad> works

Seems to be a domain name server thing - I'll take a look at it this evening

Regards

Russell Watson

**Comment by nilswald** [comment]
this calls for a [good issue label] label
